baseURL: "https://rbolt2.netlify.app/"
languageCode: "en-us"
DefaultContentLanguage: en
title: Randi Bolt
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
taxonomies:
  category: categories
  series: series
  tag: tags
