baseURL: https://example.com
languageCode: en
DefaultContentLanguage: en
title: Website of Jane Doe
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
taxonomies:
  category: categories
  series: series
  tag: tags
