---
title: Latex
author: Randi Bolt
date: '2022-01-06'
slug: latex-hacks
categories:
  - undergrad
tags:
  - latex
  - undergrad
---

Here is some short and simple latex that I often find helpful. 

### Basic Symbols : 

- $\sim$ : `\sim`

- $\circ$ : `\circ`

- $\square$ : `\square`

- $\equiv$ : `\equiv`

- $\cong$ : `\cong`

- $\div$ : `\div`

- $\emptyset$ : `\emptyset`

- $\subseteq$ : `\subseteq`

- $a\choose b$ : `a\choose b`

- $\Leftrightarrow$ : `\Leftrightarrow`

- $\langle\rangle$ : `\langle\rangle`

- $\overrightarrow{\rm AB}$ : `\overrightarrow{\rm AB}`

- $\underline{\text{Underline Text}}$ : `\underline{\text{Underline Text}}`

- $\mathbb{R}$ : `\mathbb{R}` 

  - bb : blackboard bold 
  
- $\mathcal{F}$ : `\mathcal{F}`

- $\mathscr{F}$ : `\mathscr{F}`

### Inline : 

**Limits above and below sums and integrals** 

- $\sum\limits_{n}^{i}\int_0^1$ : `\limits`

**Matrices and Matrix Equations** 

- $\begin{smallmatrix} 1 & 0 \\ 0 & 1\end{smallmatrix}$ : `\begin{smallmatrix} 1 & 0 \\ 0 & 1\end{smallmatrix}`

  - $I=[\begin{smallmatrix} 1 & 0 \\ 0 & 1\end{smallmatrix}]$
  
  - $(\begin{smallmatrix} 1 & 1 \\ 1 & 0\end{smallmatrix})(\begin{smallmatrix} 1 & 1 \\ 0 & 1\end{smallmatrix})\ne(\begin{smallmatrix} 1 & 1 \\ 0 & 1\end{smallmatrix})(\begin{smallmatrix} 1 & 1 \\ 1 & 0\end{smallmatrix})$

### Multiple Lines : 

**Function** 

- $F(x)=\begin{cases}1 & x\geq 0\\0 & \text{otherwise}\end{cases}$ : `F(x)=\begin{cases} . . . \end{cases}`

  - `1 & x \geq 0 \\`
  
  - `0 & \text{otherwise}`
  
**Series of Equalities** 

- $\begin{equation}\label{a}\begin{split}x &= a+b+c\\&=1+2+3\\&=6\end{split}\end{equation}$ : `\begin{equation}\{label}\begin{split}... \end{split}\end{equation}'

  - `x &= a+b+c \\`

  - `&= 1+2+3`
  
  - `&= 6` 

### Advice :

**Google Docs Equations Boxes**

- Most latex backslashes work in google doc's equation boxes. If I have to do a "quick" homework, and dont want to spend a lot of time formatting a pdf in R, I will use google docs, and these shortcuts in the equations boxes.  

  - Note that before I started using R this is how I began learning latex.
