---
title: Group Theory Midterm Prep.
author: Randi Bolt
date: '2022-02-07'
slug: []
categories:
  - undergrad
tags:
  - math
  - sets 
  - subsets
  - operations
  - commutative
  - associative
  - identity
  - inverses
  - groups
  - abelian groups
  - cancellation law
  - propositions and theorems on group
  - subgroups, functions, injective
  - surjective, bijective, permutation
  - symmetric groups, cycles
  - cycle decomposition
  - disjoint cycles
  - inverse of a cycle
  - length and transposition
  - Transposition Parity Theorem
  - isomorphisms
  - Cayley's Theorem
---

These notes are to help me prepare for MTH-344, Group Theory Applications midterm. 

# Set 

A set is an un-ordered collection on objects. 

### Examples 

- $\mathbb{N}=\{1,2,3,...\}$ : they exist naturally

- $\mathbb{Z}=\{...,-3,-2,-1,0,1,2,3,...\}$ : includes zero and negatives
  
- $\mathbb{Q}=\{\frac{m}{n}|m,n\in \mathbb{Z}\text{ and }n\ne 0\}$ : integer fractions 
  
- $\mathbb{R}$ : includes square roots and pie, real analysis starts with $\sqrt{2}$

- $\mathbb{C}$ : includes imaginary numbers 
  
- Asterisk in the superscript means delete zero 

- Plus sign in the superscript means only positive values (>0)

# Subset 

A set B is a subset of A, $B\subseteq A$ if every element of B is an element of A. 

# Operations 

An operation $*$ on a set A is a rule which assigns to each ordered pair (a,b) of elements A exactly one element $a*b$ of A.

## Properties

1. `*` is **commutative** if $a\ne b$, $a*b=b*a$ $\forall$ a,b $\in A$. 

    - `+` and $\cdot$ are commutative 

    - `-` , $\div$ , funtion composition and matrix multiplication are not commutative 

2. `*` is **associative** if $(a*b)*c=a*(b*c)$ $\forall$ a,b,c, $\in A$. 

    - addition is associative, subtraction is not associative 
  
3. If $\exists$ $e\in A$ $\Rightarrow$ $e*a=a*e=a$ $\forall$ $a\in A$, the we call e the **identity element** in A w.r.t. `*`. 

    - 0=e w.r.t. addition

    - 1=e w.r.t. multiplication 

4. If $e\in A$ is the identity w.r.t. `*` and $a,b\in A\Rightarrow$ $a*b=b*a=e$ we call a and b **inverses** of one another. 

    - the inverse of $a\in \mathbb{R}$ w.r.t. addition is -a since $a+(-a)=(-a)+a=0$
    
    - the inverse of $a\in\mathbb{R}^*$ w.r.t. multiplication is $\frac{1}{a}$ since $a(\frac{1}{a})=(\frac{1}{a})a=1$
    
## Proof Outlines

1. Commutative: 

    $\underline{\text{No}}$: Give an example, "Let a = 1, and b =2", and then show $a*b\ne b*a$.
    
    $\underline{\text{Yes}}$: "For any a,b in the set" and then show $a*b=b*a$. 

 2. Associative 
 
    $\underline{\text{No}}$: Give an example, "Let a=1, b=2, c=3" and then show $a*(b*c)\ne (a*b)*c$.  
    
    $\underline{\text{Yes}}$: "For any a,b,c in the set" and then show $a*(b*c)=(a*b)*c$. 
    
3. Identity 
 
    $\underline{\text{No}}$: Suppose that $e\in$ the given set $\Rightarrow$ $a*e=a$ $\forall a\in$ the given set. Then show $a*e=a$ by plugging e in for b and solving for e. "Since the identity element must be a constant then there is no identiy w.r.t." the given set.  (can't involve variables)
    
    $\underline{\text{Yes}}$: State what the identity element is w.r.t. the orperation and show that $a*e=a$ and $e*a=a$.

4. Inverses 
 
    $\underline{\text{No}}$: Given an example of an element who doesn't have an inverse. 
    
    Note: If there is not identity element then there is no inverse. 
    
    $\underline{\text{Yes}}$: "Suppose b=$a^{-1}$. Then $a*b=e$" (where e is the identity found in 3), and then try to solve the eqation for b. Then check $b*a=e$ as well.
    
    Note: Do not need to check $b*a=e$ if we know `*` is commutative. 
    
# Group

Let G be a set and `*` be an operation on G. Suppose 

i. `*` is associative

ii. $\exists$ $e\in G$

iii. $\forall$ $a\in G\Rightarrow a^{-1}\in G$.

- for finite groups $|G|<\infty$

# Abelian Group 

A group that is also commutative. 

- If G is abelian, then $(ab)^n=a^nb^n$ for all $n\in \mathbb{N}$. 
    
# Propositions and Theorems for Groups

## Proposition 1

Let G be a group, then G has exactly one idently element. 

## Proposition 2

Every element of G has exactly one inverse. 

## Theorem 1 (Cancellation Law)

Let G be a group and let $a,b,c\in G$, then $ab=ac\Rightarrow b=c$ and $ba=ca\Rightarrow b=c$. 

## Theorem 2

Let G be a group and let $a,b\in G$. If $ab=e$, then a and b are inverses, i.e. $a=b^{-1}$ and $b=a^{-1}$.

## Theorem 3

Let G be a group and let $a,b\in G$ then $(ab)^{-1}=b^{-1}a^{-1}$ and $(a^{-1})^{-1}=a$. 

- to show a and b are inverses, show their product is e.

### Klein 4 Goup

(for fintie groups) : $a^2=b^2=c^2=e$

# Homework 1 Questions 

1. `b)` Do the following operations define a given set: $a*b=3^b$ on $\mathbb{Q}$? 

No, this does not define an operation on $\mathbb{Q}$ because $a*b$ is not always in $\mathbb{Q}$. For example, let $a=1$ and $b=\frac{1}{2}$. Then $a*b=1*\frac{1}{2}=3^{\frac{1}{2}}=\sqrt{3}\not\in\mathbb{Q}$. 

6. Suppose a,b and x are element of a non-abelian group G, and that we want to solve the equation ax=b for x. Why would it be incorrect and unclear to say that the solution is $x=\frac{b}{a}$? 

When we write $x=\frac{b}{a}$ it is unclear if we mean $x=a^{-1}b$ or $x=ba^{-1}$. Since G is a nonabelian group, $a^{-1}b$ and $ba^{-1$ are not necessarily equal. The correct answer to $ax=b$ is $x=a^{-1}b$. 

# Subgroups

Let G be a group. A subset $H\subseteq G$ is called a subgroup if:

i. $e\in H$ (same e as G)

ii. $\forall$ a,b $\in H$ $ab\in H$. (we say H is closed under the operation)

iii. $\forall$ $a\in H$ , $a^{-1}\in H$. (we say H is closed under inverses)

### Example

Addition: i) $0\in H$. ii) $\forall$ a,b $\in H$ $a+b=H$. iii) $\forall$ $a\in H$ , $-a\in H$.   
    
## Proof Outlines (Two-Step Subgroup Test)

i. $e\in H$

ii. for all a,b $\in H$, $ab^{-1}\in H$. 

Prove something is a subgroup of G. 

i. "Suppose" then show e is 0 or 1 for the subgroup in a short series of equalities, "the additive or multiplicative element 0 or 1 is in" the subgroup. 

ii. "Now take any a,b $\in$ the subgroup." Then define a and b potentially for some other integers. Then show $ab^{-1}=$ something identifiably in the subgroup. 

"Therefore we've shown that" our subgroup "contains the identity element and for all a,b $\in H$ , $ab^{-1}\in$" our subgroup. Thus our subgroup is a subgroup of G. 

### Example

Addition: 

i. $0\in H$.

ii. for all $a,b\in H$, $a+(-b)=a-b\in H$. 

## Added Notes

1. If G is abelian, then $(ab)^n=a^nb^n$ for all $n\in \mathbb{N}$. 

2. In any group $(a^{-1})^n=(a^n)^{-1}$ for all $n\in \mathbb{N}$.

3. In any group $e^{-1}=e$.

## Two-step subgroup test

Let G be a group. A subset H $\subseteq G$ is a subgroup of G if 

i. $e\in H$

  - addition: show 0 $\in H$

ii. $\forall a,b,\in H$, $ab^{-1}\in H$. 

  - addition: $\forall$ a,b $\in H$, $a+(-b)=a-b\in H$
  
# HW 2 Questions 

2. Prove H is a subgroup of G for: $H=\{3^m4^n|m,n\in\mathbb{Z}\}$, $G=\mathbb{R}^*$

Since $1=3^04^0$, the multiplicative identity element 1 is in H. 

Now take any a,b $\in H$. Then $a=3^{m_1}4^{n_1}$ and $b=3^{m_2}4^{n_2}$ for some $m_1, m_2, n_1, n_2 \in \mathbb{Z}$. So, 

$ab^{-1} = 3^{m_1}4^{n_1}(3^{m_2}4^{n_2})^{-1}$

$\quad\quad= 3^{m_1}4^{n_1}\cdot \frac{1}{3^{m_2}4^{n_2}}$

$\quad\quad= \frac{3^{m_1}}{3^{m_2}}\cdot\frac{4^n_1}{4^n_2}\quad\quad\quad\quad\text{, since multiplication is commutative}$

$\quad\quad= 3^{m_1-m_2}4^{n_1-n_2}$

Since $\mathbb{Z}$ is closed under subtraction, $m_1-m_2$ and $n_1-n_2$ are in $\mathbb{Z}$. Therefore, 

$$ab^{-1}=3^{m_1-m_2}4^{n_1-n_2}\in H$$

We've shown that H contains the identity element and for all a,b $\in H$, $ab^{-1}\in H$. Thus, H is a subgroup of $\mathbb{R}^*$. $\quad\quad\square$

5. Let H be a subgroup of group G and let $a\in G$ be a constant. Show that $K=\{aha^{-1}|h\in H\}$ is also a subgroup of G. 

Since H is a subgroup of G, the idnetity element e is in H. Hence, $aea^{-1}\in K$. 

Since, $aea^{-1}=aa^{-1}=e$, this implies that $e\in K$. 

Now take any elements $ah_1a^{-1}$ and $ah_2a^{-1}$ in K. Then $h_1$, $h_2$ $\in H$ and 

$ah_1a^{-1}(ah_2a^{-1})^{-1}=ah_1a^{-1}(a^{-1})^{-1}h_2^{-1}a^{-1}\quad\quad\quad\text{, by T. 3(i) form Ch. 4}$

$\quad\quad\quad\quad\quad\quad\quad\quad=ah_1a^{-1}ah_2^{-1}a^{-1}\quad\quad\quad\quad\quad\text{ , by T.3(ii) from Ch. 4}$

$\quad\quad\quad\quad\quad\quad\quad\quad=ah_1h_2^{-1}a^{-1}\quad\quad\quad\quad\quad\quad\quad\text{, since }a^{-1}a=e$

Since H is a subgroup of G and $h_1$, $h_2$ $\in H$, the element $h_1h_2^{-1}$ is in H. Hence 

$$ah_1a^{-1}(ah_2a^{-1})^{-1}=ah_1h_2^{-1}a^{-1}\in K$$

Completing the proof that K is ia subgroup of H. 


# Functions

Let A and B be sets. A function $f$ from A to B is a rule that assigns to each element $a\in A$ exactly one element in $f(a)\in B$. 

For f to transform $G_1$ to $G_2$ then $\forall$ a,b $\in G$ we want f to take $ab\in G$ to the element $f(a)f(b)\in G_2$. 

## Injective

A function $f:A\rightarrow B$ is injective or one-to-one if $f(x_1)=f(x_2)$ $\Rightarrow$ $x_1=x_2$. 

## Surjective

A function $f:A\rightarrow B$ is surjectie or onto if for all $y\in B$ there exists $x\in A$ such that $f(x)=y$. 

## Bijective
 
A function $f:A\Rightarrow B$ is bijectie because f is both one-to-one and onto. 

## Proof Outline : Bijection, proving injective and surjective

1. Injective

"Suppose for some $x_1, x_2\in G$," then show $f(x_1)=f(x_2)$ $\Rightarrow$ $x_1=x_2$. "So, f is one-to-one".

2. Surjective

"Take any y $\in G$. We need to find $x\in G\Rightarrow f(x)=y$." Then solve for x, and check that the x you found works for $f(x)=y$. "Therefore f is also onto". 

"We've shown that $f$ is injective and surjective. So by definition, f is a bijection from G to G". 

# Composition

Let $f:A\rightarrow B$ and $a:B\rightarrow C$. The composition of f with g is the function $g\circ f:A\rightarrow C$ defined $(g\circ f)(x)=g(f(x))$.

# Inverse

The inverse of a function $f:A\rightarrow B$ is the function $f^{-1}:B\rightarrow A$ satisfying $f(x)=y\Leftrightarrow f^{-1}(y)=x$. 

A function $f:A\rightarrow B$ has an inverse $f^{-1}:B\rightarrow A$ if and only if f is bijective. 

To find an inverse function write $y=f(x)$, solve for x, and switch the x's and y's to get the formula for $f^{-1}$. 

# Permutation

A permutation of a set A is a bijection from A to A. 

Another way to think of it is as a rearrangement of the order of elements in a set. 

# Symmetric Group

Let A be a set. The symmetric group on A, denoted $S_A$ is the group of all permutation of A with the operation of function composition. 

# Permuation Group

A permutation group is any symmetric group or any subgroup of a symmetric group. 

# Identity Permutation $\epsilon$

The identity permutation is the function $\epsilon : A\rightarrow A$ define $\epsilon(x)=x$. 

# Cycle

Example: $f=(\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7\\ 5 & 3 & 1 & 7 & 2 & 6 & 4\end{smallmatrix})\in S_7$

## Cycle Decomposition 

Example: $\Rightarrow f=(1523)(47)$

## Disjoint Cyccle

We call two cycles disjoint if they have no numbers in common.

Disjoint cycles in $S_n$ commute. 

## Inverse of a Cycle 

Example: $f^{-1}=(\begin{smallmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7\\ 3 & 5 & 2 & 7 & 1 & 6 & 4\end{smallmatrix})$

## Length and Transposition 

The number of integers in a cycle is called its length. 

A cycle of length 2 is called a transposition. 

# Theorem 8.2 Transpoision Parity

When writing a permutation as a composition of trasnpositions, the parity (even/ odd) of the number of transpositions is unique. 

- even length implies odd permutation 

- even + odd = odd

# Isomorphism

A function $f:G_1\rightarrow G_2$ is called an isomorphism if f is a bijection and for all $a,b\in G$ $f(ab)=f(a)f(b)$.

## Isomorphism Proposition 1

Let f: $G_1\rightarrow G_2$ be an isomorphism. Then 

i. $f(e_1)=e_2$

ii. $\forall a\in G$, f(a) and $f(a)^{-1}$ are inverese in $G_2$, i.e. $f(a^{-1})=[f(a)]^{-1}$

iii. If $G_1=\langle a\rangle$, then $G_2=\langle f(a)\rangle$. 

## $\cong$ Groups have the same algebraic properties

Suppose $G_1\cong G_2$. Then, 

1. $|G_1|=|G_2|$ (they have the same size)

2. $G_1$ is abelian $\Leftrightarrow$ $G_2$ is abelian.
 
3. $G_1$ is cyclic $\Leftrightarrow$ $G_2$ is cyclic. 

4. $G_1$ has the property that every element squared equals e $\Leftrightarrow$ $G_2$ has the same property. 

5. Every subgroup of $G_1$ is isomorphic to a subgroup of $G_2$. 

and so on... 

## Groups Size 4

Every group of size 4 is isomorphic to $\mathbb{Z_}_4$ or $\mathbb{Z}_2\times\mathbb{Z}_2$. (We proved that those two are not isomorphic to each other)

# Cayley's Theorem 

Every group is ismorphic to a permutation group. 




    
  