---
title: 'rvest '
author: Randi
date: '2022-03-19'
slug: []
categories: []
tags: []
---


```{r}
install.packages("quantmod", type = "binary")
```

```{r}
library(quantmod) # data 
library(tidyverse) # clean 
library(tibble) # change row names to first column
library(prophet) # predict
```

```{r}
quantmod::getSymbols("MVIS")
head(MVIS)
```

```{r}
MVIS <- data.frame(MVIS)
head(MVIS)
```


```{r}
MVIS <- tibble::rownames_to_column(MVIS, "ds")
```


```{r}
# Tidy 
MVIS <- MVIS %>%
  mutate(ds = str_remove(ds, "X"),
         ds = str_replace_all(ds, "[.]","-"),
         ds = as.Date(ds))
head(MVIS)
# CLosing Data 
MVIS_close <- data.frame(ds = MVIS$ds, y = MVIS$MVIS.Close)
head(MVIS_close)
```

```{r}
# call prophet function to fit the model 
Model1 <- prophet(MVIS_close, daily.seasonality=TRUE)
Future1 <- make_future_dataframe(Model1, periods = 730)
tail(Future1)
```


```{r}
# Forecast Proper 
Forecast1 <- predict(Model1, Future1)
tail(Forecast1[c("ds", "yhat", "yhat_lower", "yhat_upper")])
```
```{r}
dyplot.prophet(Model1, Forecast1)
```

```{r}
prophet_plot_components(Model1, Forecast1)
```





```{r}
OR_unemployment <- getSymbols("ORUR", src = "FRED", auto.assign = F)
```

https://www.youtube.com/watch?v=5W7VZCHZAQY

```{r}
library(openssl)

sha256("hello")
```

